services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - db
      - minio
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpw
    ports:
      - "3306:3306"
    networks:
      - app
  minio:
    image: bitnami/minio:2024
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpw
      MINIO_DEFAULT_BUCKETS: files
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app

volumes:
  db-data:
  minio:

networks:
  app: